name: test
on: [push]
jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
    steps:
      - name: Get libmysqlcppconn9
        uses: wei/wget@v1
        if: matrix.os == 'ubuntu-latest'
        with:
          args: https://dev.mysql.com/get/Downloads/Connector-C++/libmysqlcppconn9_8.0.28-1debian11_amd64.deb
      - name: Get libmysqlcppconn8
        uses: wei/wget@v1
        if: matrix.os == 'ubuntu-latest'
        with:
          args: https://dev.mysql.com/get/Downloads/Connector-C++/libmysqlcppconn8-2_8.0.28-1debian11_amd64.deb
      - name: Get libmysqlcppconn-dev
        uses: wei/wget@v1
        if: matrix.os == 'ubuntu-latest'
        with:
          args: https://dev.mysql.com/get/Downloads/Connector-C++/libmysqlcppconn-dev_8.0.28-1debian11_amd64.deb
      - name: Expand libmysqlcppconn8
        if: matrix.os == 'ubuntu-latest'
        run: dpkg -X libmysqlcppconn9_8.0.28-1debian11_amd64.deb /tmp/libmysqlcppconn
      - name: Expand libmysqlcppconn9
        if: matrix.os == 'ubuntu-latest'
        run: dpkg -X libmysqlcppconn8-2_8.0.28-1debian11_amd64.deb /tmp/libmysqlcppconn
      - name: Expand libmysqlcppconn-dev
        if: matrix.os == 'ubuntu-latest'
        run: dpkg -X libmysqlcppconn-dev_8.0.28-1debian11_amd64.deb /tmp/libmysqlcppconn
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build
        run: bazelisk build //main:hello
      - name: Test
        run: bazelisk test test:hello
