name: test
on: [push]
jobs:
  test-linux:
    name: Test Linux
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Docker Compose Up
        run: docker compose up -d
      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash
      - name: Build
        run: docker compose exec dev bazel build main:hello
      - name: Test
        run: docker compose exec dev bazel test test:hello

  test-windows:
    name: Test Windows
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build
        run: bazelisk build main:hello
      - name: Test
        run: bazelisk test test:hello
