name: test
on: [push]
jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Test
        run: bazelisk test test:hello-test
      - name: Build
        run: bazelisk build //main:hello-world
